Creating initialization_utils and adapting main for output format
PedroH-Reis/Task-Scheduling-ACO pull request #7
Opened 2021-03-21 09:50 UTC by matheuskja

2021-03-21 21:13 UTC, PedroH-Reis requested changes

2021-03-21 21:13 UTC, PedroH-Reis commented on .gitignore
> +teste/*
there is a functions called test.py where you can put your tests in.

you can add this to the projet, because they can be automated tests, i think there is no problem

2021-03-21 21:13 UTC, PedroH-Reis commented on src/initialization_utils.py
> +    # print(eta)
print =D

2021-03-21 21:13 UTC, PedroH-Reis commented on src/initialization_utils.py
> +    pass
can be remove since not used

2021-03-21 21:13 UTC, PedroH-Reis commented on src/main.py
> +	# pheromone = initializePheromone(ET) # Matheus
feel free to remove this comments

2021-03-21 21:13 UTC, PedroH-Reis commented on src/initialization_utils.py
> +    eta = sum_time/nTaks
actually, eta cannot be a real number, because for each task it will have a different value.

ETAij = the inverse of execution time when task j runs in processor i

2021-03-21 21:13 UTC, PedroH-Reis commented on src/initialization_utils.py
> +    initializionPheromone = (1/eta)*np.ones((nTaks,nTaks))
so, the pheromone is not the inverse of eta

it is actually the mean value of all execution times

Pheromone0_ij = the mean value of all execution times

2021-03-22 09:09 UTC, matheuskja commented on .gitignore
> +teste/*
Fair enough! I'll add after the unit tests there!

2021-03-22 09:09 UTC, matheuskja commented on src/initialization_utils.py
> +    # print(eta)
HAHAHAAH I forgot to remove the comments! my bad!

2021-03-22 09:11 UTC, matheuskja commented on src/initialization_utils.py
> +    eta = sum_time/nTaks
Ohh I see! I changed it! thanks!
For the moment, all rows are the same, right?  Since we have that a task will take the same time in any processor

2021-03-22 12:14 UTC, PedroH-Reis approved these changes

2021-03-22 12:28 UTC, merged